repos:
  - repo: https://kgithub.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      # list of supported hooks: https://pre-commit.com/hooks.html
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: debug-statements
      - id: detect-private-key

  # python code formatting
  - repo: https://kgithub.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
        args: [--line-length, "99"]

  # python import sorting
  - repo: https://kgithub.com/PyCQA/isort
    rev: 5.8.0
    hooks:
      - id: isort

  # yaml formatting
  - repo: https://kgithub.com/pre-commit/mirrors-prettier
    rev: v2.3.0
    hooks:
      - id: prettier
        types: [yaml]

  # python code analysis
  - repo: https://kgithub.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
      - id: flake8

  - repo: https://kgithub.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
      - id: mypy
        exclude: ^(docs/|example-plugin/)
